---
- name: Generate configuration file
  template: src=vSCa-vba-lo-6880.lo0.j2 dest=~/ansible/cfgs/{{item.site_prefix}}-vsc-a.txt
  with_items:
    - {site_prefix: bld, b1: 1, x1: 6 }
    - {site_prefix: pok, b1: 2, x1: 7 } 
    - {site_prefix: sms, b1: 3, x1: 8 }
    - {site_prefix: rtp, b1: 4, x1: 9 }
    - {site_prefix: hpr, b1: 5, x1: 0 }

